language: julia

os:
  - linux

julia:
  - 1.4
  - 1.5
  - nightly

arch:
  - amd64

branches:
  only:
    - master
    - dev
    - /^travis-.*$/
    - /^release-.*$/
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/

notifications:
  email: false

jobs:
  exclude:
    - os: osx
      arch: x86
    - os: windows
      arch: x86
  include:
    - stage: "Documentation 1.4"
      julia: 1.4
      os: linux
      arch: amd64
      script:
        - julia docs/make.jl
    - stage: "Documentation 1.5"
      julia: 1.5
      os: linux
      arch: amd64
      script:
        - julia docs/make.jl
    - stage: "Documentation nightly"
      julia: nightly
      os: linux
      arch: amd64
      script:
        - julia docs/make.jl
